version: '3.9'

services:
  # mongo DB service
  mongo_db:
    image: mongo
    container_name: mongodb_container
    restart: always
    env_file:
      - ./.env.dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - linkedin-clone
    

  

  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      
      - /node_modules
    networks:
      - linkedin-clone
    env_file:
      - ./.env.dev
    depends_on:
      - mongo_db
    restart: on-failure
    command: >
         npm run dev
           
networks:
  linkedin-clone:
    driver: bridge

volumes:
  mongo_data: {}
 